apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.destination.repo }}
  annotations:
    github.com/project-slug: ${{values.destination.owner}}/${{values.destination.repo}}
  description: ${{ values.destination.repo }} created by Crossplane
spec:
  type: cluster
  owner: user:guest
  lifecycle: experimental