apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.destination.repo }}
  annotations:
    github.com/project-slug: ${{values.destination.owner}}/${{values.destination.repo}}
    backstage.io/kubernetes-label-selector: 'app=${{values.appName}}'
  description: ${{ values.destination.repo }} created
spec:
  type: service
  owner: user:guest
  lifecycle: experimental